### ISSUE TITLE
js-api docs

### ISSUE THREAD

**Issue by gitaaron** [functionland/docs#37]
how to invoke our JS library SDK

**Comment by gitaaron** [comment]
I agree we'll rename 'BOX Api' to 'FULA Api' - create a separate [issue](https://github.com/functionland/docs/issues/44) for it.

This issue is mainly to fill out what is going in '[Using the FULA Client library](https://docs.fx.land/getting-started/fula-client)'

@farhoud is still working on samples for 'Working with file objects'  [here](https://github.com/functionland/fula/issues/60) and [here](https://github.com/functionland/fula/issues/59)  - can we wait until those are complete then revisit in docs?

The stuff here -

```
Working with JSON objects
Queries
Mutations
Filter Objects
Subscribe to data changes
```

Sounds good to me - can we create separate issues for  them and maybe have a conversation about it first?

**Comment by gitaaron** [comment]
BTW - one change @farhoud and I were discussing here is to change the API from something like `fulaClient.sendFileStream` to `fulaClient.file.sendStream` 

I personally prefer the latter is there is a more natural grouping with everything under 'file' and 'data'.  We could also maybe in the future have 'fulaClient.auth' for everything under 'auth'.

**Comment by mehdibalouchi** [comment]
> BTW - one change @farhoud and I were discussing here is to change the API from something like fulaClient.sendFileStream to fulaClient.file.sendStream

this is actually what I was asking about in the first place. If we are going to group interfaces then the documentation structure can be identical to the interfaces.

**Comment by gitaaron** [comment]
> > BTW - one change @farhoud and I were discussing here is to change the API from something like fulaClient.sendFileStream to fulaClient.file.sendStream
> 
> this is actually what I was asking about in the first place. If we are going to group interfaces then the documentation structure can be identical to the interfaces.

OK great - so leave docs structure as is and make the change to `fulaClient.file.*` and `fulaClient.data.*` ?

**Comment by gitaaron** [comment]
- connect  / close
- getNode (interacting with underlying libp2p)
	- for going under the covers
