### ISSUE TITLE
design doc: private network

### ISSUE THREAD

**Issue by gitaaron** [functionland/docs#63]
One use case might be for a [geographically distributed data-reserve to prevent loss](https://github.com/functionland/docs/pull/61)

**Comment by farhoud** [comment]
> > Base on my experience we can still use Rely v2 and webrtc signaling server for hole punching
> 
> Where are the relay  v2s/webrtc signalling servers coming from?  Who is providing them?
> 
> Note:  this  is continuation of conversation starting here - https://github.com/functionland/docs/issues/60#issuecomment-1072769551

Public ipfs infestructure and node's

**Comment by farhoud** [comment]
You can test it our js implimention, you can pass the pkey and still listen on public ipfs webrtc signaling servers

**Comment by gitaaron** [comment]
@masih - you mentioned we can work around the lack of public bootstrappers by finding our own way to provision each BOX with a peer list.

What about the lack of public relays?  I am looking at [IPFS cluster architecture](https://cluster.ipfs.io/documentation/deployment/architecture/) and it mentions -

```
This also means that Cluster peers operate separately from IPFS with regards to NAT hole punching, ports etc.
```

I am interpreting this as we will have to setup our own relays?

**Comment by masih** [comment]
There are two separate things that I see here: one is bootstrapping, and the other is connectivity over NAT.

We don't need public node to do bootstrapping. As for the latter, you are correct. We either use existing relays or need to set up our own for connectivity to work over NAT. 

If I recall correctly there is a separate issue captured, dedicated to investigating NAT traversal? Would it make sense to leave the NAT related issues to that and focus on the simpler case for now?

**Comment by gitaaron** [comment]
Hi @masih the [nat traversal](https://github.com/functionland/docs/issues/28) issue I raised a few weeks back is related but a little different.  In that scenario we are assuming we have full access to public relays.

My question here is more a clarification around the line in the ipfs-cluster docs regarding NAT hole punching. 

> This also means that Cluster peers operate separately from IPFS with regards to NAT hole punching, ports etc.

I am  wondering what the docs mean by 'operate separately'.   My assumption is they mean we are unable to make use of public  relays and will have to set up our own ( ? )

**Comment by masih** [comment]
Correct

**Comment by gitaaron** [comment]
Ok thanks - a follow-up question is who is going to provide the relays we are using here?

A few thoughts -

1.  Can we make use of the public relays then upgrade to a private network somehow?  If the answer is 'yes' then I would also ask if BOX customers should rely on public infra. for any use case involving replication?

2. Perhaps data syncing can simply be a paid service in the fula network?  The resource miner in this case would be a relay.
